services:
  angular-service: # The name of the service
    container_name: angularcontainer  # Container name
    build: ./front/xmlFrontend # Location of our Dockerfile
    ports:
      - '4200:4200' # Port mapping
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"

  auth-services:
    image: 'auth'
    build:
      context: ./services/auth-services
    container_name: auth
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/XML_auth
      - SPRING_DATASOURCE_USERNAME=xml
      - SPRING_DATASOURCE_PASSWORD=0000

  campaign-services:
    image: 'campaign'
    build:
      context: ./services/campaign-services
    container_name: campaign
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/XML_campaign
      - SPRING_DATASOURCE_USERNAME=xml
      - SPRING_DATASOURCE_PASSWORD=0000

  notification-services:
    image: 'notification'
    build:
      context: ./services/notification-services
    container_name: notification
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/XML_notification
      - SPRING_DATASOURCE_USERNAME=xml
      - SPRING_DATASOURCE_PASSWORD=0000

  db:
    image: 'postgres:latest'
    restart: always
    container_name: db
    ports:
      - 5433:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres