services:
  angular-service: # The name of the service
    container_name: angularcontainer  # Container name
    build: ./front/xmlFrontend # Location of our Dockerfile
    ports:
      - '4200:4200' # Port mapping
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    volumes:
      - ./front/xmlFrontend/src/assets/pictures:/assets/pictures

  agent-front-service: # The name of the service
    container_name: agentFront  # Container name
    build: ./front/agentApp # Location of our Dockerfile
    ports:
      - '4300:4300' # Port mapping
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4300"
    volumes:
      - ./front/agentApp/src/assets/pictures:/assets/pictures

  auth-services:
    image: 'auth'
    build:
      context: ./services/auth-services
    container_name: auth
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/XML_auth
      - SPRING_DATASOURCE_USERNAME=xml
      - SPRING_DATASOURCE_PASSWORD=0000
    ports:
      - 8090:8090

  agent-app-services:
    image: 'agent-app'
    build:
      context: ./services/agent-app-services
    container_name: agent-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/XML
      - SPRING_DATASOURCE_USERNAME=xml
      - SPRING_DATASOURCE_PASSWORD=0000
    ports:
      - 8150:8150

  campaign-services:
    image: 'campaign'
    build:
      context: ./services/campaign-services
    container_name: campaign
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/XML_campaign
      - SPRING_DATASOURCE_USERNAME=xml
      - SPRING_DATASOURCE_PASSWORD=0000
    ports:
      - 8100:8100

  notification-services:
    image: 'notification'
    build:
      context: ./services/notification-services
    container_name: notification
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/XML_notification
      - SPRING_DATASOURCE_USERNAME=xml
      - SPRING_DATASOURCE_PASSWORD=0000
    ports:
      - 8110:8110

  picture-video-services:
    image: 'picture-video'
    build:
      context: ./services/picture-video-services
    container_name: picture-video
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/XML_picture_video
      - SPRING_DATASOURCE_USERNAME=xml
      - SPRING_DATASOURCE_PASSWORD=0000
    ports:
      - 8120:8120
    volumes:
      - ./front/xmlFrontend/src/assets/pictures:/assets/pictures

  post-services:
    image: 'post'
    build:
      context: ./services/post-services
    container_name: post
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/XML_post
      - SPRING_DATASOURCE_USERNAME=xml
      - SPRING_DATASOURCE_PASSWORD=0000
    ports:
      - 8130:8130

  profile-services:
    image: 'profile'
    build:
      context: ./services/profile-services
    container_name: profile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/XML_profile
      - SPRING_DATASOURCE_USERNAME=xml
      - SPRING_DATASOURCE_PASSWORD=0000
    ports:
      - 8140:8140

  db:
    image: 'postgres:latest'
    restart: always
    container_name: db
    ports:
      - 5433:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  gateway:
    build: ./services/Gateway
    container_name: gateway
    ports:
      - 80:80
    depends_on:
      - profile-services