CREATE ROLE xml WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD '0000';

CREATE DATABASE "XML"
    WITH 
    OWNER = xml
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;
	
CREATE DATABASE "XML_auth"
    WITH 
    OWNER = xml
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;
	
CREATE DATABASE "XML_campaign"
    WITH 
    OWNER = xml
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;
	
CREATE DATABASE "XML_notification"
    WITH 
    OWNER = xml
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;
	
CREATE DATABASE "XML_picture_video"
    WITH 
    OWNER = xml
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;
	
CREATE DATABASE "XML_post"
    WITH 
    OWNER = xml
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;
	
CREATE DATABASE "XML_profile"
    WITH 
    OWNER = xml
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;